include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  # -----------------------------------------
  # Your other keyboard parts here
  # -----------------------------------------
  # Change the board appropriately, you 4can use any board
  - board: nice_nano
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset

  # Add these cmake-args to the peripherals you wish to use with the dongle
  # board: nice_nano
  #  shield: my_keyboard
   # cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

